# Generated by Django 5.2.7 on 2025-10-22 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_3166_1', models.CharField(help_text="ISO 3166-1 code, e.g. 'DE', 'IE'", max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['iso_3166_1'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_639_1', models.CharField(help_text="ISO 639-1 code, e.g. 'en', 'de'", max_length=2, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['iso_639_1'],
            },
        ),
        migrations.CreateModel(
            name='CountryName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(help_text="The name of the country as expressed in the naming language (e.g. 'Alemania')", max_length=100)),
                ('country_named', models.ForeignKey(help_text="The country being named (e.g. 'DE')", on_delete=django.db.models.deletion.CASCADE, related_name='names', to='ui_locale.country')),
                ('naming_language', models.ForeignKey(help_text="The language used for naming (e.g. 'es')", on_delete=django.db.models.deletion.CASCADE, related_name='country_naming', to='ui_locale.language')),
            ],
            options={
                'verbose_name': 'Country Name',
                'verbose_name_plural': 'Country Names',
                'ordering': ['country_named__iso_3166_1'],
                'constraints': [models.UniqueConstraint(fields=('country_named', 'naming_language'), name='unique_country_name')],
            },
        ),
        migrations.CreateModel(
            name='LanguageName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(help_text='The name of the language as expressed in the naming language', max_length=100)),
                ('language_named', models.ForeignKey(help_text="The language being named (e.g. 'en')", on_delete=django.db.models.deletion.CASCADE, related_name='names', to='ui_locale.language')),
                ('naming_language', models.ForeignKey(help_text="The language used for naming (e.g. 'de')", on_delete=django.db.models.deletion.CASCADE, related_name='naming', to='ui_locale.language')),
            ],
            options={
                'verbose_name': 'Language Name',
                'verbose_name_plural': 'Language Names',
                'ordering': ['language_named__iso_639_1'],
                'constraints': [models.UniqueConstraint(fields=('language_named', 'naming_language'), name='unique_language_name')],
            },
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_supported', models.BooleanField(default=False)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui_locale.country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_locale.language')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('language', 'country'), name='unique_locale')],
            },
        ),
    ]
