# Generated by Django 5.2.7 on 2025-10-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui_locale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locale',
            options={'verbose_name': 'Locale', 'verbose_name_plural': 'Locales'},
        ),
    ]
