# Generated by Django 5.2.7 on 2025-10-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'User settings', 'verbose_name_plural': 'User settings'},
        ),
    ]
